name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to latest version
        
      - name: Show exact file content and test secrets
        run: |
          echo "----- TESTING SECRETS -----"
          echo "PlantNet key length: ${#PLANTNET_API_KEY}"
          echo "Gemini key length: ${#GEMINI_API_KEY}"
          echo "First 4 chars of PlantNet: ${PLANTNET_API_KEY:0:4}"
          echo "First 4 chars of Gemini: ${GEMINI_API_KEY:0:4}"
          echo ""
          echo "----- EXACT HTML CONTENT AROUND API KEYS -----"
          grep -A 2 -B 2 "API_KEY" index.html
          echo ""
          echo "----- SHOWING HEX DUMP OF PROBLEMATIC LINES -----"
          grep "API_KEY" index.html | head -5 | hexdump -C
        env:
          PLANTNET_API_KEY: ${{ secrets.PLANTNET_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
      - name: Force replacement using sed (nuclear option)
        run: |
          echo "Before replacement:"
          grep "PLANTNET_API_KEY" index.html | head -3
          
          # Use different delimiters and escape everything
          sed -i "s#__PLANTNET_API_KEY__#${PLANTNET_API_KEY}#g" index.html
          sed -i "s#__GEMINI_API_KEY__#${GEMINI_API_KEY}#g" index.html
          
          echo "After replacement:"
          grep "PLANTNET_API_KEY\|${PLANTNET_API_KEY:0:10}" index.html | head -3
        env:
          PLANTNET_API_KEY: ${{ secrets.PLANTNET_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      
      - name: Debug API Key Injection
        run: |
          echo "----- CHECKING API KEY INJECTION -----"
          echo "Looking for PlantNet key pattern:"
          grep -n "PLANTNET_API_KEY.*=" index.html | head -3
          echo "Looking for Gemini key pattern:"
          grep -n "GEMINI_API_KEY.*=" index.html | head -3
          echo "Checking for any remaining placeholders:"
          if grep -q "__.*_API_KEY__" index.html; then
            echo "❌ WARNING: Found unreplaced placeholders!"
            grep -n "__.*_API_KEY__" index.html
          else
            echo "✅ No placeholders found - injection appears successful"
          fi
          echo "--------------------------------------"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
