name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject API Keys
        run: |
          sed -i "s|__PLANTNET_API_KEY__|$PLANTNET_API_KEY|g" index.html
          sed -i "s|__GEMINI_API_KEY__|$GEMINI_API_KEY|g" index.html
        env:
          PLANTNET_API_KEY: ${{ secrets.PLANTNET_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Debug replaced index.html
        run: |
          echo "----- INDEX.HTML CONTENT PREVIEW -----"
          head -n 50 index.html
          echo "--------------------------------------"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
