name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test secrets and simple replacement
        run: |
          echo "=== CHECKING SECRETS ==="
          if [ -n "$PLANTNET_API_KEY" ]; then
            echo "✅ PLANTNET_API_KEY exists (length: ${#PLANTNET_API_KEY})"
          else
            echo "❌ PLANTNET_API_KEY is missing!"
          fi
          
          if [ -n "$GEMINI_API_KEY" ]; then
            echo "✅ GEMINI_API_KEY exists (length: ${#GEMINI_API_KEY})"
          else
            echo "❌ GEMINI_API_KEY is missing!"
          fi
          
          echo ""
          echo "=== BEFORE REPLACEMENT ==="
          grep -n "PLANTNET_KEY_HERE\|GEMINI_KEY_HERE" index.html || echo "No simple placeholders found"
          grep -n "API_KEY" index.html | head -5
          
          echo ""
          echo "=== SIMPLE REPLACEMENT ==="
          sed -i "s/PLANTNET_KEY_HERE/$PLANTNET_API_KEY/g" index.html
          sed -i "s/GEMINI_KEY_HERE/$GEMINI_API_KEY/g" index.html
          
          echo "=== AFTER REPLACEMENT ==="
          grep -n "const.*API_KEY" index.html | head -5
          
          echo ""
          echo "=== CHECKING FOR UNREPLACED PLACEHOLDERS ==="
          if grep -q "PLANTNET_KEY_HERE\|GEMINI_KEY_HERE" index.html; then
            echo "❌ Still have unreplaced simple placeholders!"
            grep "PLANTNET_KEY_HERE\|GEMINI_KEY_HERE" index.html
          else
            echo "✅ Simple placeholders replaced successfully!"
          fi
          
        env:
          PLANTNET_API_KEY: ${{ secrets.PLANTNET_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
